"""
Email Alert Service
Sends notifications for critical events: stockouts, fraud, sentiment drops.
Uses SMTP (Gmail, SendGrid, or any SMTP server).
"""

import smtplib
import os
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from datetime import datetime
import logging

logger = logging.getLogger(__name__)

SMTP_HOST = os.getenv("SMTP_HOST", "smtp.gmail.com")
SMTP_PORT = int(os.getenv("SMTP_PORT", 587))
SMTP_USER = os.getenv("SMTP_USER", "")
SMTP_PASS = os.getenv("SMTP_PASS", "")
ALERT_EMAIL = os.getenv("ALERT_EMAIL", "")


def send_alert(subject: str, body_html: str, to_email: str = None) -> bool:
    """
    Send an HTML email alert. Returns True on success.
    Silently logs and returns False if SMTP is not configured.
    """
    to = to_email or ALERT_EMAIL
    if not all([SMTP_USER, SMTP_PASS, to]):
        logger.warning("Email alert skipped — SMTP not configured.")
        return False

    try:
        msg = MIMEMultipart("alternative")
        msg["Subject"] = f"[SalesAI Alert] {subject}"
        msg["From"]    = SMTP_USER
        msg["To"]      = to

        # Plain text fallback
        plain = body_html.replace("<br>", "\n").replace("</p>", "\n")
        msg.attach(MIMEText(plain, "plain"))
        msg.attach(MIMEText(body_html, "html"))

        with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
            server.ehlo()
            server.starttls()
            server.login(SMTP_USER, SMTP_PASS)
            server.sendmail(SMTP_USER, to, msg.as_string())

        logger.info(f"Alert email sent to {to}: {subject}")
        return True

    except Exception as e:
        logger.error(f"Failed to send alert email: {e}")
        return False


def alert_stockout(product_name: str, units_left: int, days_remaining: float):
    subject = f"CRITICAL: {product_name} stockout in {days_remaining:.1f} days"
    html = f"""
    <h2 style="color:#ef4444">🚨 Stockout Alert</h2>
    <p><strong>Product:</strong> {product_name}</p>
    <p><strong>Units Remaining:</strong> {units_left}</p>
    <p><strong>Days Until Stockout:</strong> {days_remaining:.1f}</p>
    <p><strong>Action Required:</strong> Place reorder immediately.</p>
    <p style="color:#6b7280;font-size:12px">Generated by SalesAI at {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}</p>
    """
    send_alert(subject, html)


def alert_fraud(alert_type: str, message: str):
    subject = f"FRAUD ALERT: {alert_type.replace('_', ' ').title()}"
    html = f"""
    <h2 style="color:#ef4444">⚠️ Fraud Detection Alert</h2>
    <p><strong>Type:</strong> {alert_type}</p>
    <p><strong>Details:</strong> {message}</p>
    <p><strong>Action Required:</strong> Review flagged transactions immediately.</p>
    <p style="color:#6b7280;font-size:12px">Generated by SalesAI at {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}</p>
    """
    send_alert(subject, html)


def alert_sentiment_drop(product_name: str, neg_pct: float, trending_issues: list):
    subject = f"Sentiment Alert: {product_name} negative reviews at {neg_pct:.0f}%"
    issues_html = "".join(f"<li>{i}</li>" for i in trending_issues)
    html = f"""
    <h2 style="color:#f59e0b">💬 Customer Sentiment Alert</h2>
    <p><strong>Product:</strong> {product_name}</p>
    <p><strong>Negative Sentiment:</strong> {neg_pct:.1f}%</p>
    <p><strong>Trending Complaints:</strong></p>
    <ul>{issues_html}</ul>
    <p>Please review and take corrective action.</p>
    <p style="color:#6b7280;font-size:12px">Generated by SalesAI at {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}</p>
    """
    send_alert(subject, html)
